### ISSUE TITLE
API for CifraClub plataform

### ISSUE THREAD

**Issue by GuiSousa135** [More-Than-Solitaire/Tabs-Lite#100]
It would be very interesting to add more APIs from different platforms focused on tabs/cifras/partitions, allowing to increase the scope of possible songs and artists in the app. I highly recommend the CifraClub website (cifraclub.com) which has a large database of many songs for different instruments (but i don't know if have any public API).

Your app is amazing!

**Comment by cullub** [comment]
I'm not against adding other tab sources, but if there's not a public open API it's probably not worth it at the moment.  If another developer wanted to add this functionality, they'd hopefully only have to reimplement this class: https://github.com/More-Than-Solitaire/Tabs-Lite/blob/master/app/src/main/java/com/gbros/tabslite/utilities/UgApi.kt
