### ISSUE TITLE
Save scroll speed to db

### ISSUE THREAD

**Issue by cullub** [More-Than-Solitaire/Tabs-Lite#11]
Scroll speed used on a song should be remembered and sent to the database.  Default database value should be null in case we change default values in the code.

**Comment by cullub** [comment]
This would cause problems since we don't save the text size to the database.

**Comment by Yralec** [comment]
Hi cullub,
Could this be reopened?

Even without text size being saved scroll speed would still be very useful.
In [Issue 75](https://github.com/More-Than-Solitaire/Tabs-Lite/issues/75) there's also a secondary request for scrolling speed to be saved.

If it can be reopened I'd be happy to work on it.

**Comment by cullub** [comment]
I reopened this, and added the feature to the latest release. Scroll speed is now saved (although on a whole-app basis as a preference). Feel free to open another issue if you'd like improvements to this feature.
