### ISSUE TITLE
Support different types (instruments) of tabs

### ISSUE THREAD

**Issue by cullub** [More-Than-Solitaire/Tabs-Lite#50]
It would be nice to be able to search for uke and bass tabs as well.  Has to be configurable though bc most might not need those

**Comment by cullub** [comment]
Idea: have this be a setting that basically just chooses which chords to show for the tab on clicking them.

**Comment by cullub** [comment]
Related: #51

**Comment by AndydeCleyre** [comment]
For me having uke is a good fallback for disagreeable or absent chords entries for a song.

**Comment by cullub** [comment]
Closing as duplicate of #66, feel free to add information to that issue instead.
