### ISSUE TITLE
Export/Import tabs from file

### ISSUE THREAD

**Issue by Cabeda** [More-Than-Solitaire/Tabs-Lite#76]
Hi! 

First, thanks for the app 🙏🏼 . 

One feature I'd like to propose would be the ability to export and import the list of tabs and playlists from a file (i.e json). In this way, no account would be needed and we could back up and restore easily. In the current state if one switches phone or does a factory reset will lose everything.

**Comment by dnr101** [comment]
Where are the tab files stored in the file structure? It would be great even to be able to make a backup of that folder..

**Comment by cullub** [comment]
Hey there, this is on the list of things I'd like to add, but since it's a side project for me it does usually take quite a while to add new features.  If you're interested in looking into things, I use the Kotlin Room database to store the data, so that might be a starting point.

**Comment by cullub** [comment]
Hi all, this feature was added in the latest release. Tap the TabsLite icon on the home screen and then click Export in the TabsLite menu. Thanks for requesting it!
