### ISSUE TITLE
Publish app to F-Droid

### ISSUE THREAD

**Issue by platinorum** [More-Than-Solitaire/Tabs-Lite#77]
Hi,

I really like your app, so I wanted to ask if you maybe want to publish it to the F-Droid repository, since this is where many, if not most people search for open source apps.

**Comment by gabmert** [comment]
In the meantime see the izzysoft repo https://apt.izzysoft.de/fdroid/index/apk/com.gbros.tabslite

**Comment by khimaros** [comment]
the versions of this app on GH releases as well as Izzy are very outdated. the only location being maintained seems to be Play Store

**Comment by cullub** [comment]
Hey all, I've updated the releases on this page, and the izzysoft repo should be able to be updated soon.  Although I'd love to publish to FDroid, the app currently contains google play services which makes it not allowable for fdroid.  I may update it at some point but it's not a high priority for me at the moment.
