### ISSUE TITLE
Barre chord aren't shown anymore in tabs graph

### ISSUE THREAD

**Issue by Choucroute-melba** [More-Than-Solitaire/Tabs-Lite#82]
Hi, since the last update the panel doesn't show any barre chord, I don't know if it's hard to fix but it would be cool if they are back.

And thanks for your work, this app is really perfect for people like me who are looking for a simple free solution 🙂

**Comment by cullub** [comment]
Hi thank you for noticing this! I think this is fixed in the latest update, could you confirm?
