### ISSUE TITLE
Crash on open link into tabs

### ISSUE THREAD

**Issue by black00019** [More-Than-Solitaire/Tabs-Lite#86]
Hi i have the latest version 3.3.9
In this tab:
https://tabslite.com/tabs/832924 "Poprocks And Coke bt Green Day"
This  is link to youtube, but when i click the app crash and close

Thanks

**Comment by cullub** [comment]
Confirmed this issue, thanks for reporting.  I'll try to get this fixed in the next update.

**Comment by cullub** [comment]
Fixed in code, pending testing and push to prod.  New fix: If opening link directly fails, copy to clipboard
