### ISSUE TITLE
Make deleting songs from playlist accidentally a bit more difficult

### ISSUE THREAD

**Issue by maqp** [More-Than-Solitaire/Tabs-Lite#91]
Hi, first of all, thank you for a very responsive and easy to use app.

I just spent a good while adding songs I like to play to a playlist, but accidentally managed to swipe sideways twice, and I have no idea which songs I deleted. I suspect this is bound to happen to not just me while in use.

So would it be possible to have a confirmation dialog for deleting songs, and/or a hovering undo button for a few seconds after deleting a song from the playlist, to get accidentally deleted songs back.

**Comment by cullub** [comment]
Thanks!  That's a great idea, I'll look into that.

**Comment by MarkusOttela** [comment]
Wohoo :tada: Thank You so much!

**Comment by cullub** [comment]
Added issue #111 for that bug. Thanks.
